### ISSUE TITLE
关于wooyun-firefox

### ISSUE THREAD

**Issue by m4d3bug** [lxj616/wooyun-firefox#1]
你好，了解了一圈firefox低版本安装与渗透插件安装，发现wooyun-firefox才是解决方案，但是关于你readme里提及的参照woobuntu的build脚本，没有发现有wooyun-firefox的踪影，希望得到你的帮助，谢谢

**Comment by lxj616** [comment]
该项目已经不再维护，建议参考https://github.com/mazen160/Firefox-Security-Toolkit 中的插件使用最新版本firefox然后自己安装

**Comment by m4d3bug** [comment]
好的，感谢
